title: Geometric Kernels
description: A cross-framework package for kernels and Gaussian processes on manifolds, graphs, and meshes
markdown: kramdown
plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
header_menu:
    -
        title: "Home"
        link: "/#home"
    -
        title: "Get Started"
        link: "/#getstarted"
    -
        title: "Code"
        link: "/#code"
    -
        title: "Documentation"
        link: "/#documentation"
    -
        title: "Examples"
        link: "/#examples"
defaults:
    - scope:
        path: "_posts/current"
      values:
        layout: post
        category: current
    - scope:
        path: "_posts/archive"
      values:
        layout: post
        category: archive
        