title: Geometric Kernels
description: A cross-framework package for kernels and Gaussian processes on manifolds, graphs, and meshes
markdown: kramdown
plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
header_pages:
    -
        title: "Home"
        url: "/#home"
    -
        title: "Get Started"
        url: "/#getstarted"
    -
        title: "Code"
        url: "/#code"
    -
        title: "Documentation"
        url: "/#documentation"
    -
        title: "Examples"
        url: "/#examples"